name: Cleanup deployments and build coverage

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  build:
    needs: cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Настройка QEMU и Buildx для расширенной сборки и кэширования
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Кэш Docker слоёв
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Сборка Docker-образа с использованием кэша
      - name: Build Docker image with cache
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          tags: s21containers
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Основная сборка и вычисление покрытия из Makefile (как и было)
      - name: Run build and coverage using Makefile
        run: make build && make coverage

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage

      - name: List coverage directory
        run: ls -la build/coverage

      - name: Deploy coverage report to GitHub Pages
        if: github.ref == 'refs/heads/rb_tree' || github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/coverage

